services:
  - type: web
    name: samvidha-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn samvidha_api:app
    autoDeploy: true
cronJobs:
  - name: keep-alive
    schedule: "*/5 * * * *"  # every 5 minutes
    url: https://samvidha-backend.onrender.com/

